### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by eduardoinnorway** [jonschlinkert/grunt-refactor#3]
npm ERR! fetch failed https://github.com/cloudhead/less.js/tarball/1.5.0-wip
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:58:12)
npm ERR!     at WriteStream.emit (events.js:117:20)
npm ERR!     at evalmachine.<anonymous>:1609:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/eduardo/IdeaProjects/grunt-refactor-master
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0

**Comment by honzatrtik** [comment]
please, update devDependencies - #4

**Comment by Andreas-Schoenefeldt** [comment]
Yes please :+1:

**Comment by mrmoree** [comment]
yes!!! thx

**Comment by su-narthur** [comment]
@honzatrtik's pull request #4 works. Would be great if this could get merged in.
